\\ Phase 1 worker: for every prime p in [P1_A, P1_B], every prime ideal P | p with
\\ N(P) <= P1_BOUND is shown to lie in the subgroup of Cl(L) generated by the
\\ factor base, by PARI's own bnftestprimes() code restricted to this p-range
\\ (see pari-2.19.0-bnftestprimes-range.patch). An ideal that cannot be split
\\ would make SPLIT loop or raise an error, never pass silently.
\\ Env: FIELD, P1_A, P1_B, P1_BOUND, P1_OUT, optional BNF.
read("certify/fields.gp");
install("bnftestprimes_range", "vGGGG");

phase1_main() =
{
  my(a = eval(getenv("P1_A")), b = eval(getenv("P1_B")), bound = eval(getenv("P1_BOUND")));
  my(out = getenv("P1_OUT"), B = read(bnfpath()), t0 = getabstime(), f);
  if (B.no != 1, error("bnf class number != 1"));
  bnftestprimes_range(B, a, b, bound);
  f = fileopen(out, "w");
  filewrite(f, Str("range ", a, " ", b, " bound ", bound));
  filewrite(f, Str("primes ", primepi(b) - primepi(a - 1), " ms ", getabstime() - t0));
  filewrite(f, "STATUS OK");
  fileclose(f);
}

phase1_main();
quit;
